[2025-02-04T11:27:48.837+0000] {processor.py:186} INFO - Started process (PID=677) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:27:48.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:27:48.841+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:48.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:27:48.882+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:27:48.997+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:48.996+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:LocalIngestionDAG
[2025-02-04T11:27:49.010+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:49.010+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:LocalIngestionDAG
[2025-02-04T11:27:49.022+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:49.021+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:LocalIngestionDAG
[2025-02-04T11:27:49.034+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:49.033+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:LocalIngestionDAG
[2025-02-04T11:27:49.044+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:49.043+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:LocalIngestionDAG
[2025-02-04T11:27:49.054+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:49.053+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:LocalIngestionDAG
[2025-02-04T11:27:49.064+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:49.064+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:LocalIngestionDAG
[2025-02-04T11:27:49.065+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:49.065+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:27:49.079+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:49.079+0000] {dag.py:3262} INFO - Creating ORM DAG for LocalIngestionDAG
[2025-02-04T11:27:49.090+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:27:49.090+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to None, run_after=None
[2025-02-04T11:27:49.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.281 seconds
[2025-02-04T11:28:19.831+0000] {processor.py:186} INFO - Started process (PID=741) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:28:19.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:28:19.837+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:28:19.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:28:19.862+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:28:19.884+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:28:19.884+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:28:19.915+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:28:19.915+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to None, run_after=None
[2025-02-04T11:28:19.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.118 seconds
[2025-02-04T11:28:27.530+0000] {processor.py:186} INFO - Started process (PID=747) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:28:27.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:28:27.537+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:28:27.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:28:27.566+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:28:27.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:28:27.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:28:27.598+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.075 seconds
[2025-02-04T11:28:57.794+0000] {processor.py:186} INFO - Started process (PID=811) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:28:57.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:28:57.798+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:28:57.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:28:57.820+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:28:57.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:28:57.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:28:57.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.054 seconds
[2025-02-04T11:29:28.052+0000] {processor.py:186} INFO - Started process (PID=875) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:29:28.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:29:28.055+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:29:28.055+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:29:28.077+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:29:28.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:29:28.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:29:28.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.055 seconds
[2025-02-04T11:29:59.046+0000] {processor.py:186} INFO - Started process (PID=939) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:29:59.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:29:59.050+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:29:59.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:29:59.073+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:29:59.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:29:59.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:29:59.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.067 seconds
[2025-02-04T11:30:29.929+0000] {processor.py:186} INFO - Started process (PID=1003) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:30:29.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:30:29.932+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:30:29.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:30:29.953+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:30:29.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:30:29.954+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:30:29.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.055 seconds
[2025-02-04T11:31:00.332+0000] {processor.py:186} INFO - Started process (PID=1068) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:31:00.333+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:31:00.335+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:31:00.335+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:31:00.358+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:31:00.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:31:00.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:31:00.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.052 seconds
[2025-02-04T11:31:27.617+0000] {processor.py:186} INFO - Started process (PID=1127) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:31:27.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:31:27.620+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:31:27.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:31:27.644+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:31:27.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:31:27.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:31:27.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.058 seconds
[2025-02-04T11:31:57.738+0000] {processor.py:186} INFO - Started process (PID=1191) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:31:57.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:31:57.741+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:31:57.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:31:57.761+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:31:57.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:31:57.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:31:57.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.060 seconds
[2025-02-04T11:32:28.800+0000] {processor.py:186} INFO - Started process (PID=1255) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:32:28.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:32:28.802+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:32:28.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:32:28.819+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:32:28.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:32:28.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:32:28.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.044 seconds
[2025-02-04T11:32:59.796+0000] {processor.py:186} INFO - Started process (PID=1319) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:32:59.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:32:59.798+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:32:59.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:32:59.818+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:32:59.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:32:59.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:32:59.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.059 seconds
[2025-02-04T11:33:30.755+0000] {processor.py:186} INFO - Started process (PID=1383) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:33:30.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:33:30.760+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:33:30.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:33:30.800+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:33:30.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:33:30.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:33:30.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.083 seconds
[2025-02-04T11:34:01.466+0000] {processor.py:186} INFO - Started process (PID=1447) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:34:01.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:34:01.468+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:34:01.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:34:01.488+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:34:01.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:34:01.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:34:01.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.059 seconds
[2025-02-04T11:34:32.455+0000] {processor.py:186} INFO - Started process (PID=1511) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:34:32.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:34:32.458+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:34:32.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:34:32.484+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:34:32.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:34:32.485+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:34:32.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.060 seconds
[2025-02-04T11:35:02.629+0000] {processor.py:186} INFO - Started process (PID=1575) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:35:02.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:35:02.632+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:35:02.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:35:02.657+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:35:02.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:35:02.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:35:02.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.071 seconds
[2025-02-04T11:35:33.360+0000] {processor.py:186} INFO - Started process (PID=1639) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:35:33.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:35:33.363+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:35:33.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:35:33.385+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:35:33.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:35:33.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:35:33.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.051 seconds
[2025-02-04T11:36:04.287+0000] {processor.py:186} INFO - Started process (PID=1703) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:36:04.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:36:04.290+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:36:04.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:36:04.312+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:36:04.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 8
    "LocalIngestionDAG"
    ^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:36:04.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:36:04.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.050 seconds
[2025-02-04T11:36:15.954+0000] {processor.py:186} INFO - Started process (PID=1709) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:36:15.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:36:15.958+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:36:15.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:36:16.028+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:36:16.018+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:36:16.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:36:16.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.109 seconds
[2025-02-04T11:36:46.447+0000] {processor.py:186} INFO - Started process (PID=1779) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:36:46.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:36:46.449+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:36:46.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:36:46.472+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:36:46.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:36:46.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:36:46.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.054 seconds
[2025-02-04T11:37:16.660+0000] {processor.py:186} INFO - Started process (PID=1843) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:37:16.662+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:37:16.663+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:37:16.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:37:16.687+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:37:16.681+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:37:16.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:37:16.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.057 seconds
[2025-02-04T11:37:47.480+0000] {processor.py:186} INFO - Started process (PID=1907) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:37:47.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:37:47.484+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:37:47.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:37:47.508+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:37:47.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:37:47.511+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:37:47.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.068 seconds
[2025-02-04T11:38:18.175+0000] {processor.py:186} INFO - Started process (PID=1971) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:38:18.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:38:18.178+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:38:18.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:38:18.207+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:38:18.199+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:38:18.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:38:18.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.062 seconds
[2025-02-04T11:38:48.561+0000] {processor.py:186} INFO - Started process (PID=2035) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:38:48.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:38:48.564+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:38:48.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:38:48.587+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:38:48.582+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:38:48.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:38:48.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.056 seconds
[2025-02-04T11:39:18.985+0000] {processor.py:186} INFO - Started process (PID=2099) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:39:18.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:39:18.988+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:39:18.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:39:19.008+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:39:19.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:39:19.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:39:19.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.057 seconds
[2025-02-04T11:39:49.435+0000] {processor.py:186} INFO - Started process (PID=2163) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:39:49.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:39:49.439+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:39:49.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:39:49.459+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:39:49.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:39:49.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:39:49.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.051 seconds
[2025-02-04T11:40:20.056+0000] {processor.py:186} INFO - Started process (PID=2227) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:40:20.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:40:20.059+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:40:20.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:40:20.077+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:40:20.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:40:20.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:40:20.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.055 seconds
[2025-02-04T11:40:50.927+0000] {processor.py:186} INFO - Started process (PID=2291) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:40:50.928+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:40:50.931+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:40:50.930+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:40:50.956+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:40:50.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:40:50.958+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:40:50.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.057 seconds
[2025-02-04T11:41:21.829+0000] {processor.py:186} INFO - Started process (PID=2355) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:41:21.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:41:21.832+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:41:21.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:41:21.859+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:41:21.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:41:21.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:41:21.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.068 seconds
[2025-02-04T11:41:52.905+0000] {processor.py:186} INFO - Started process (PID=2419) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:41:52.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:41:52.909+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:41:52.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:41:52.931+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:41:52.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:41:52.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:41:52.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.054 seconds
[2025-02-04T11:42:23.443+0000] {processor.py:186} INFO - Started process (PID=2483) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:42:23.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:42:23.446+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:42:23.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:42:23.468+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:42:23.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:42:23.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:42:23.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.061 seconds
[2025-02-04T11:42:53.714+0000] {processor.py:186} INFO - Started process (PID=2547) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:42:53.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:42:53.717+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:42:53.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:42:53.737+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:42:53.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:42:53.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:42:53.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.053 seconds
[2025-02-04T11:43:24.607+0000] {processor.py:186} INFO - Started process (PID=2611) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:43:24.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:43:24.610+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:43:24.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:43:24.629+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:43:24.624+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:43:24.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:43:24.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.049 seconds
[2025-02-04T11:43:55.381+0000] {processor.py:186} INFO - Started process (PID=2675) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:43:55.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:43:55.384+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:43:55.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:43:55.407+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:43:55.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:43:55.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:43:55.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.063 seconds
[2025-02-04T11:44:25.611+0000] {processor.py:186} INFO - Started process (PID=2739) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:44:25.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:44:25.614+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:44:25.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:44:25.643+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:44:25.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:44:25.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:44:25.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.065 seconds
[2025-02-04T11:44:56.649+0000] {processor.py:186} INFO - Started process (PID=2803) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:44:56.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:44:56.651+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:44:56.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:44:56.676+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:44:56.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:44:56.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:44:56.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.058 seconds
[2025-02-04T11:45:27.172+0000] {processor.py:186} INFO - Started process (PID=2867) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:45:27.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:45:27.175+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:45:27.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:45:27.195+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:45:27.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:45:27.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:45:27.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.058 seconds
[2025-02-04T11:45:57.752+0000] {processor.py:186} INFO - Started process (PID=2931) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:45:57.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:45:57.754+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:45:57.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:45:57.776+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:45:57.771+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:45:57.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:45:57.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.052 seconds
[2025-02-04T11:46:28.795+0000] {processor.py:186} INFO - Started process (PID=2995) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:46:28.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:46:28.798+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:46:28.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:46:28.817+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:46:28.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:46:28.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:46:28.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.059 seconds
[2025-02-04T11:46:59.464+0000] {processor.py:186} INFO - Started process (PID=3059) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:46:59.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:46:59.467+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:46:59.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:46:59.490+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:46:59.483+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:46:59.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:46:59.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.052 seconds
[2025-02-04T11:47:29.675+0000] {processor.py:186} INFO - Started process (PID=3123) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:47:29.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:47:29.677+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:47:29.677+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:47:29.697+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:47:29.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:47:29.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:47:29.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.059 seconds
[2025-02-04T11:48:00.594+0000] {processor.py:186} INFO - Started process (PID=3187) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:48:00.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:48:00.598+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:48:00.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:48:00.622+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:48:00.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:48:00.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:48:00.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.059 seconds
[2025-02-04T11:48:30.963+0000] {processor.py:186} INFO - Started process (PID=3251) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:48:30.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:48:30.965+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:48:30.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:48:30.987+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:48:30.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:48:30.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:48:31.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.063 seconds
[2025-02-04T11:49:01.470+0000] {processor.py:186} INFO - Started process (PID=3315) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:49:01.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:49:01.473+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:49:01.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:49:01.492+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:49:01.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:49:01.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:49:01.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.058 seconds
[2025-02-04T11:49:32.402+0000] {processor.py:186} INFO - Started process (PID=3379) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:49:32.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:49:32.405+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:49:32.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:49:32.428+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:49:32.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:49:32.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:49:32.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.056 seconds
[2025-02-04T11:50:02.766+0000] {processor.py:186} INFO - Started process (PID=3443) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:50:02.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:50:02.769+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:50:02.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:50:02.797+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:50:02.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:50:02.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:50:02.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.069 seconds
[2025-02-04T11:50:34.033+0000] {processor.py:186} INFO - Started process (PID=3507) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:50:34.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:50:34.036+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:50:34.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:50:34.060+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:50:34.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 7, in <module>
    local_workflow = DAG(
                     ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 650, in __init__
    raise ValueError("DAG is missing the start_date parameter")
ValueError: DAG is missing the start_date parameter
[2025-02-04T11:50:34.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:50:34.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.064 seconds
[2025-02-04T11:50:45.179+0000] {processor.py:186} INFO - Started process (PID=3508) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:50:45.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:50:45.182+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:50:45.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:50:45.203+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:50:45.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 9
    schedule_interval="0 6 2 * *"
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:50:45.204+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:50:45.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.051 seconds
[2025-02-04T11:51:15.817+0000] {processor.py:186} INFO - Started process (PID=3572) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:51:15.818+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:51:15.819+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:51:15.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:51:15.839+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:51:15.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 9
    schedule_interval="0 6 2 * *"
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:51:15.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:51:15.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.051 seconds
[2025-02-04T11:51:46.655+0000] {processor.py:186} INFO - Started process (PID=3636) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:51:46.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:51:46.658+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:51:46.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:51:46.681+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:51:46.680+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 9
    schedule_interval="0 6 2 * *"
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:51:46.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:51:46.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.052 seconds
[2025-02-04T11:52:17.170+0000] {processor.py:186} INFO - Started process (PID=3700) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:52:17.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:52:17.172+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:52:17.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:52:17.203+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:52:17.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 9
    schedule_interval="0 6 2 * *"
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:52:17.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:52:17.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.059 seconds
[2025-02-04T11:52:47.415+0000] {processor.py:186} INFO - Started process (PID=3764) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:52:47.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:52:47.418+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:52:47.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:52:47.450+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:52:47.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 9
    schedule_interval="0 6 2 * *"
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:52:47.451+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:52:47.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.076 seconds
[2025-02-04T11:53:17.999+0000] {processor.py:186} INFO - Started process (PID=3834) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:53:18.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:53:18.002+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:53:18.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:53:18.026+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:53:18.025+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 9
    schedule_interval="0 6 2 * *"
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:53:18.027+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:53:18.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.055 seconds
[2025-02-04T11:53:48.828+0000] {processor.py:186} INFO - Started process (PID=3898) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:53:48.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:53:48.831+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:53:48.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:53:48.862+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:53:48.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 9
    schedule_interval="0 6 2 * *"
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-02-04T11:53:48.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:53:48.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.071 seconds
[2025-02-04T11:53:53.969+0000] {processor.py:186} INFO - Started process (PID=3899) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:53:54.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:53:54.044+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:53:54.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:53:54.072+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:53:54.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 10
    start_date= datetime(2025,3,3);
                                  ^
SyntaxError: invalid syntax
[2025-02-04T11:53:54.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:53:54.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.129 seconds
[2025-02-04T11:54:24.889+0000] {processor.py:186} INFO - Started process (PID=3963) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:54:24.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:54:24.892+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:54:24.891+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:54:24.914+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:54:24.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_localdb.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_localdb.py", line 10
    start_date= datetime(2025,3,3);
                                  ^
SyntaxError: invalid syntax
[2025-02-04T11:54:24.915+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:54:24.935+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.052 seconds
[2025-02-04T11:54:46.819+0000] {processor.py:186} INFO - Started process (PID=4021) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:54:46.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:54:46.821+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:54:46.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:54:46.857+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:54:46.964+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:54:46.963+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:54:46.988+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:54:46.988+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:54:47.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.213 seconds
[2025-02-04T11:55:17.092+0000] {processor.py:186} INFO - Started process (PID=4085) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:55:17.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:55:17.095+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:55:17.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:55:17.118+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:55:17.139+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:55:17.139+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:55:17.166+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:55:17.165+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:55:17.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.105 seconds
[2025-02-04T11:55:47.744+0000] {processor.py:186} INFO - Started process (PID=4156) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:55:47.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:55:47.746+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:55:47.746+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:55:47.767+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:55:47.786+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:55:47.786+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:55:47.810+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:55:47.810+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:55:47.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.109 seconds
[2025-02-04T11:56:18.811+0000] {processor.py:186} INFO - Started process (PID=4220) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:56:18.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:56:18.814+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:56:18.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:56:18.839+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:56:18.862+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:56:18.862+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:56:18.890+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:56:18.889+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:56:18.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.113 seconds
[2025-02-04T11:56:49.851+0000] {processor.py:186} INFO - Started process (PID=4284) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:56:49.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:56:49.855+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:56:49.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:56:49.877+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:56:49.898+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:56:49.898+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:56:49.924+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:56:49.924+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:56:49.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.108 seconds
[2025-02-04T11:57:20.613+0000] {processor.py:186} INFO - Started process (PID=4348) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:57:20.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:57:20.617+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:57:20.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:57:20.646+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:57:20.671+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:57:20.671+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:57:20.720+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:57:20.720+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:57:20.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.165 seconds
[2025-02-04T11:57:39.186+0000] {processor.py:186} INFO - Started process (PID=4353) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:57:39.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:57:39.189+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:57:39.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:57:39.229+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:57:39.362+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:57:39.362+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:57:39.385+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:57:39.385+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:57:39.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.237 seconds
[2025-02-04T11:58:09.580+0000] {processor.py:186} INFO - Started process (PID=4417) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:58:09.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:58:09.583+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:58:09.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:58:09.606+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:58:09.627+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:58:09.627+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:58:09.650+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:58:09.650+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:58:09.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.106 seconds
[2025-02-04T11:58:40.155+0000] {processor.py:186} INFO - Started process (PID=4481) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:58:40.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:58:40.158+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:58:40.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:58:40.188+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:58:40.224+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:58:40.223+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:58:40.266+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:58:40.266+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:58:40.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.145 seconds
[2025-02-04T11:59:10.351+0000] {processor.py:186} INFO - Started process (PID=4545) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:59:10.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:59:10.354+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:59:10.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:59:10.377+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:59:10.396+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:59:10.396+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:59:10.422+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:59:10.422+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:59:10.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.102 seconds
[2025-02-04T11:59:40.836+0000] {processor.py:186} INFO - Started process (PID=4609) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:59:40.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T11:59:40.839+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:59:40.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:59:40.860+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T11:59:40.879+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:59:40.878+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T11:59:40.906+0000] {logging_mixin.py:190} INFO - [2025-02-04T11:59:40.905+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T11:59:40.934+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.105 seconds
[2025-02-04T12:00:11.161+0000] {processor.py:186} INFO - Started process (PID=4673) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:00:11.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:00:11.163+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:00:11.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:00:11.187+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:00:11.205+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:00:11.205+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:00:11.229+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:00:11.229+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:00:11.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.109 seconds
[2025-02-04T12:00:41.444+0000] {processor.py:186} INFO - Started process (PID=4737) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:00:41.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:00:41.447+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:00:41.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:00:41.470+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:00:41.489+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:00:41.489+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:00:41.516+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:00:41.515+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:00:41.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.116 seconds
[2025-02-04T12:01:11.760+0000] {processor.py:186} INFO - Started process (PID=4801) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:01:11.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:01:11.763+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:01:11.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:01:11.785+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:01:11.809+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:01:11.809+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:01:11.832+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:01:11.832+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:01:11.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.101 seconds
[2025-02-04T12:01:42.305+0000] {processor.py:186} INFO - Started process (PID=4864) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:01:42.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:01:42.307+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:01:42.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:01:42.328+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:01:42.347+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:01:42.346+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:01:42.372+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:01:42.371+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:01:42.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.099 seconds
[2025-02-04T12:02:12.715+0000] {processor.py:186} INFO - Started process (PID=4928) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:02:12.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:02:12.718+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:02:12.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:02:12.740+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:02:12.759+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:02:12.759+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:02:12.784+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:02:12.784+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:02:12.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.107 seconds
[2025-02-04T12:02:43.591+0000] {processor.py:186} INFO - Started process (PID=4992) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:02:43.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:02:43.593+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:02:43.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:02:43.618+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:02:43.639+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:02:43.639+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:02:43.668+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:02:43.668+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:02:43.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.114 seconds
[2025-02-04T12:03:13.868+0000] {processor.py:186} INFO - Started process (PID=5056) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:03:13.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:03:13.870+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:03:13.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:03:13.894+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:03:13.915+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:03:13.914+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:03:13.939+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:03:13.939+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:03:13.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.101 seconds
[2025-02-04T12:03:44.081+0000] {processor.py:186} INFO - Started process (PID=5120) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:03:44.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:03:44.084+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:03:44.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:03:44.105+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:03:44.125+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:03:44.124+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:03:44.151+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:03:44.151+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:03:44.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.122 seconds
[2025-02-04T12:04:14.363+0000] {processor.py:186} INFO - Started process (PID=5184) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:04:14.364+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:04:14.366+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:04:14.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:04:14.388+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:04:14.409+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:04:14.408+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:04:14.433+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:04:14.433+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:04:14.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.099 seconds
[2025-02-04T12:04:44.998+0000] {processor.py:186} INFO - Started process (PID=5248) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:04:45.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:04:45.002+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:04:45.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:04:45.030+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:04:45.055+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:04:45.054+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:04:45.086+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:04:45.086+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:04:45.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.140 seconds
[2025-02-04T12:05:15.867+0000] {processor.py:186} INFO - Started process (PID=5312) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:05:15.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:05:15.871+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:05:15.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:05:15.908+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:05:15.938+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:05:15.938+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:05:15.984+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:05:15.984+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:05:16.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.167 seconds
[2025-02-04T12:05:46.694+0000] {processor.py:186} INFO - Started process (PID=5376) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:05:46.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:05:46.698+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:05:46.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:05:46.725+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:05:46.747+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:05:46.746+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:05:46.772+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:05:46.772+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:05:46.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.121 seconds
[2025-02-04T12:06:16.916+0000] {processor.py:186} INFO - Started process (PID=5440) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:06:16.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:06:16.918+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:06:16.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:06:16.939+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:06:16.958+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:06:16.958+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:06:16.983+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:06:16.983+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:06:17.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.097 seconds
[2025-02-04T12:06:47.372+0000] {processor.py:186} INFO - Started process (PID=5504) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:06:47.374+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:06:47.382+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:06:47.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:06:47.416+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:06:47.444+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:06:47.444+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:06:47.474+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:06:47.474+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:06:47.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.138 seconds
[2025-02-04T12:07:17.550+0000] {processor.py:186} INFO - Started process (PID=5568) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:07:17.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:07:17.553+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:07:17.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:07:17.574+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:07:17.593+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:07:17.593+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:07:17.619+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:07:17.618+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:07:17.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.099 seconds
[2025-02-04T12:07:48.319+0000] {processor.py:186} INFO - Started process (PID=5632) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:07:48.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:07:48.322+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:07:48.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:07:48.360+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:07:48.388+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:07:48.387+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:07:48.428+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:07:48.427+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:07:48.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.152 seconds
[2025-02-04T12:08:18.754+0000] {processor.py:186} INFO - Started process (PID=5696) to work on /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:08:18.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion_localdb.py for tasks to queue
[2025-02-04T12:08:18.757+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:08:18.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:08:18.780+0000] {processor.py:925} INFO - DAG(s) 'LocalIngestionDAG' retrieved from /opt/airflow/dags/data_ingestion_localdb.py
[2025-02-04T12:08:18.799+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:08:18.799+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T12:08:18.823+0000] {logging_mixin.py:190} INFO - [2025-02-04T12:08:18.823+0000] {dag.py:4180} INFO - Setting next_dagrun for LocalIngestionDAG to 2025-04-02 06:00:00+00:00, run_after=2025-05-02 06:00:00+00:00
[2025-02-04T12:08:18.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion_localdb.py took 0.110 seconds
